version: '3'
services:
  redis:
    image: redis
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: postgres_service
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock_app
    ports:
      - "5432:5432"